#!/usr/bin/perl -w
use strict;
use warnings;

use Time::HiRes qw(usleep);

use constant SLEEP_ON_DESKTOP_MOVE => 0.3;
use constant SLEEP_WAIT_FOR_WINDOW => 0.2;

my @resolutions = map { $_ =~ /([0-9]+)x/; $1 } grep(/[*]/, `xrandr`);

sub my_usleep {
  usleep(@_ * 1000000);
}

sub move_to_desktop {
  `wmctrl -s @_`;
  my_usleep(SLEEP_ON_DESKTOP_MOVE);
}

sub move_window_to_desktop {
  my ($window, $desktop) = @_;
  `wmctrl -r "$window" -t $desktop`;
  my_usleep(SLEEP_ON_DESKTOP_MOVE);
}

sub open_program {
  print "  launching `@_`\n";
  my ($cmd) = @_;
  system("$cmd & 2>&1 > /dev/null");
  print "  launched\n";
}

sub window_exists {
  `wmctrl -l` =~ /@_/
}

sub wait_for_window {
  my ($regex) = @_;
  print "  looking for window matching $regex\n";
  until (window_exists($regex)) {
    my_usleep(SLEEP_WAIT_FOR_WINDOW);
  }
  # print "  waited\n";
}

sub place_window {
  my ($window, $screen, $position) = @_;
  `wmctrl -r "$window" -b remove,fullscreen`;

  if ($position =~ /default/) {
    return;
  }

  # offset x position according to screen
  # sum up width of all previous screens
  my $coords_str = $position;
  if ($coords_str =~ /fullscreen/) {
    $coords_str = "0,0,0,0";
  }
  my @coords = split(',', $coords_str);
  for(0 .. $screen-1) {
    $coords[0] += $resolutions[$_]
  }
  $coords_str = join(',', @coords);
  `wmctrl -r "$window" -e 0,$coords_str`;
  print "$window $position\n";

  if ($position =~ /fullscreen/) {
    `wmctrl -r "$window" -b add,fullscreen`;
  }
}

sub run {
  my ($app, $cmd, $regex, $desktop, $screen, $position) = @_;
  print "$app\n";
  if (!window_exists($regex)) {
    print "  window doesn't exist yet\n";
    move_to_desktop($desktop);
    open_program($cmd);
    wait_for_window($regex);
  } else {
    print "  already exists. moving it to desktop $desktop\n";
    move_window_to_desktop($cmd, $desktop);
  }
  place_window($regex, $screen, $position);
}

my %config = do $ARGV[0];
my ($app, $args, $subkey, $subvalue);
while (($app, $args) = each %config) {
  my ($cmd, $regex, $desktop, $screen, $position);
  $cmd      = $args->{'cmd'}      || $app;
  $regex    = $args->{'regex'}    || $app;
  $desktop  = $args->{'desktop'}  || 0;
  $screen   = $args->{'screen'}   || 0;
  $position = $args->{'position'} || 'default';

  run($app, $cmd, $regex, $desktop, $screen, $position);
}
